// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRHJFiVrOYDpki1oUi1lFIEUdVnV1WNE',
    appId: '1:811448609722:web:4268d2b5a5aa14f3df4b83',
    messagingSenderId: '811448609722',
    projectId: 'auvnetinternshipassessment',
    authDomain: 'auvnetinternshipassessment.firebaseapp.com',
    storageBucket: 'auvnetinternshipassessment.firebasestorage.app',
    measurementId: 'G-YSNEGSJYNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgoOqr9kkxi5L3hPnNJngo_hS7p2gc10',
    appId: '1:811448609722:android:2b1ac9523129005adf4b83',
    messagingSenderId: '811448609722',
    projectId: 'auvnetinternshipassessment',
    storageBucket: 'auvnetinternshipassessment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLpVW9Frz1NSA9-hi88ve5ZtEjS9TUQg',
    appId: '1:811448609722:ios:0c1075bf9557c5e0df4b83',
    messagingSenderId: '811448609722',
    projectId: 'auvnetinternshipassessment',
    storageBucket: 'auvnetinternshipassessment.firebasestorage.app',
    iosBundleId: 'com.example.auventFlutterInternshipAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLpVW9Frz1NSA9-hi88ve5ZtEjS9TUQg',
    appId: '1:811448609722:ios:0c1075bf9557c5e0df4b83',
    messagingSenderId: '811448609722',
    projectId: 'auvnetinternshipassessment',
    storageBucket: 'auvnetinternshipassessment.firebasestorage.app',
    iosBundleId: 'com.example.auventFlutterInternshipAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRHJFiVrOYDpki1oUi1lFIEUdVnV1WNE',
    appId: '1:811448609722:web:8d43e2c002a8e006df4b83',
    messagingSenderId: '811448609722',
    projectId: 'auvnetinternshipassessment',
    authDomain: 'auvnetinternshipassessment.firebaseapp.com',
    storageBucket: 'auvnetinternshipassessment.firebasestorage.app',
    measurementId: 'G-0M690VESJ9',
  );
}
